name: 'Sync'
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'

    - name: install builer
      run: go install github.com/concrnt/emojipack-builder@v0.0.1

    - name: build
      run: emojipack-builder
      env:
        BASE_URL: ${{ secrets.BaseURL }}

    - name: sync with s3
      run: aws s3 sync . s3://${{ secrets.BUCKET_NAME }} --exclude ".*" --endpoint-url ${{ secrets.ENDPOINT_URL }} --region auto
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
